name: "Firmware CI Scheduler"
description: "Schedules a CI run on Firmware CI Runner AWS"
inputs:
  job id:
    description: "The ID of the job to run"
    required: true
  app version:
    description:
      "The version string to use for the app. This is used with the FOTA test."
    required: true
  hex file:
    description: "The location of the firmware to flash"
    required: false
    default: firmware.hex
  fota file:
    description: "The location of the firmware file to use for the FOTA test"
    required: false
    default: fota-upgrade.bin
  aws access key id:
    description: "Access Key ID for the Firmware CI Runner"
    required: true
  aws secret access key:
    description: "Secret Access Key for the Firmware CI Runner"
    required: true
  aws region:
    description: "AWS region to use"
    required: false
    default: us-west-1
  broker hostname:
    description: "AWS IoT broker hostname to use"
    required: true
  stack name:
    description: "Stack name of the cloud backend to use"
    required: false
    default: bifravst
  firmware ci device id:
    description: "ID of the IoT Thing which runs the job"
    required: true
  abort on:
    description:
      "Abortion criteria for the Firmware CI runner, will be split by newlines."
    required: false
  end on:
    description:
      "End criteria for the Firmware CI runner, will be split by newlines."
    required: false
  target:
    description: "Target board to use"
    default: "nrf9160dk_nrf9160ns"
    required: false
  network:
    description: "Network to use"
    default: "ltem"
    required: false
  sec tag:
    description: "SecTag to use for credentials"
    default: "42"
    required: false
  timeout in minutes:
    description: "Timeout for job completion in minutes"
    default: "10"
    required: false

runs:
  using: "node14"
  main: "build/index.js"
